{{- if not .Values.useStatefulSet }}
---
kind: Service
apiVersion: v1
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "fbcore.fullname" . }}
  labels:
    {{- include "fbcore.labels" . | nindent 4 }}
    firebolt/nodes-count: {{ .Values.nodesCount | quote }}
spec:
  type: ClusterIP
  # create a headless service
  clusterIP: None
  selector:
    {{- include "fbcore.selectorLabels" . | nindent 4 }}
    firebolt/nodes-count: {{ .Values.nodesCount | quote }}
  ports:
    {{- include "fbcore.servicePorts" . | nindent 4 }}
{{- end }}
