{{- if not .Values.useStatefulSet }}
{{- $nodesCount := int .Values.nodesCount }}
{{- range $i := until $nodesCount }}
---
kind: Service
apiVersion: v1
metadata:
  namespace: {{ $.Release.Namespace }}
  name: {{ include "fbcore.fullname" $ }}-{{ $i }}
  labels:
    {{- include "fbcore.labels" $ | nindent 4 }}
    firebolt/node: {{ $i | quote }}
    firebolt/nodes-count: {{ $nodesCount | quote }}
spec:
  type: ClusterIP
  # create a headless service
  clusterIP: None
  # publish the address even before being ready, otherwise the initial readiness check will never complete
  publishNotReadyAddresses: true
  selector:
    {{- include "fbcore.selectorLabels" $ | nindent 4 }}
    firebolt/node: {{ $i | quote }}
    firebolt/nodes-count: {{ $nodesCount | quote }}
  ports:
    {{- include "fbcore.servicePorts" $ | nindent 4 }}
{{- end }}
{{- end }}


